### ISSUE TITLE
Shifted screen and wrong colors

### ISSUE THREAD

**Issue by p-korzeniewski** [SuperIlu/DOjS#10]
Ok so I have a function `render()` that 
1. calls `System("wget ...")` to get a list of pixels (x,y, and color) and save them in a file
2. loads the file with `new File()`
3. clears the screen with `ClearScreen()`
4. uses `Plot()` to fill the whole screen with pixels from the file

It works fine with the first two calls, but with third call the screen is shifted to the bottom-right by about 30-40px and the colors are wrong, I can't even move mouse above that shifted position and when I move the mouse to the right it appears on the left side (just as the image). When I repeat the `render()` call, it shifts by another 30-40px as you can see on the attached screen (sorry about the quality but its a photo of the Libretto screen :D).

![dojsproblem](https://user-images.githubusercontent.com/54839623/75481079-c56c3b00-59a2-11ea-8205-253ee130e629.jpg)

**Comment by SuperIlu** [comment]
can you provide a test file and Javascript for me?
Does it happen if you just re-render the same file without calling System()?

**Comment by p-korzeniewski** [comment]
It was a problem with the batch file I was executing using `System()` - at the beginning it had instruction `CTTY NUL` to mute output from `wget` and at the end `CTTY CON` to restore output to console, but it turned out it's not needed and when I removed it everything works fine, although it's an interesting case that it always happened with the third call. Wonders of DOS :D I don't think there can be much done in DOjS besides maybe restarting the gfx similar to mouse/keyboard, but I wonder if that's even possible in Allegro?

**Comment by SuperIlu** [comment]
I deliberately didn't shutdown/restart GFX because that would clear/reinitialize the screen for every System() call.
Good that you found the problem.
Two notes before I close this:
- you could transfer BMP/PCX/TGA files and load&draw these using new Bitmap() and bm.Draw(). This way you don't have to do the drawing yourself
- next release of DOjS will contain an improved way to draw Javascript data to the screen, so no more Plot(). See my twitter for more details: https://twitter.com/dec_hl/status/1234081760855625729
